### ISSUE TITLE
t8_element_num_corners in C API

### ISSUE THREAD

**Issue by jandrej** [DLR-AMR/t8code#377] opened 2022-12-10 04:37 UTC
I have an issue where I try to generate a Julia interface with Clang.jl. When I try to use the interface function `t8_element_num_corners`, the shared object does not contain the correct symbol. Compare with `t8_element_num_faces`
```
nm  /XXX/lib/libt8.so  | grep t8_element_num_corners
0000000000024800 T _Z22t8_element_num_cornersPK16t8_eclass_schemePK10t8_element
0000000000050d10 T _ZNK26t8_default_scheme_common_c22t8_element_num_cornersEPK10t8_element
```
vs
```
nm  /XXX/lib/libt8.so  | grep t8_element_num_faces
0000000000024810 T t8_element_num_faces
0000000000051000 T _ZN23t8_default_scheme_hex_c20t8_element_num_facesEPK10t8_element
```
Somehow `t8_element_num_corners` is prefixed and Julia doesn't like that when trying to load that symbol.

Am I doing something wrong during the build of t8code?

Is it related to the const declaration of the function? (non-standard C) https://github.com/DLR-AMR/t8code/blob/f8bcd139a806144700a3d0cad64bd7a276adf662/src/t8_element_cxx.hxx#L162

**Comment by jmark** [comment] 2022-12-12 09:48
I removed a superfluous `const` in `t8_element_num_corners` signature. After the fix has been merged could you try again and report if this fixed you issue?

**Comment by holke** [comment] 2022-12-12 14:50
Yes, it looks like the `const` of the function declaration is the only difference and would cause this. Since it adds code security, we would like to keep it there...
We provide an extra pure `C` interface for this set of functions.
Can you configure your code to only use the `C` interface and not the `C++` interface?

You will find the `C` interface in https://github.com/DLR-AMR/t8code/blob/main/src/t8_element_c_interface.h

**Comment by jandrej** [comment] 2022-12-12 15:23
I don't think the problem is the interface declaration. The shared object does not include the "plain C" symbol.

**Comment by jmark** [comment] 2022-12-12 15:47
I could reproduce you result:
```
nm libt8.so | grep t8_element_num_corners
0000000000033ea0 T _Z22t8_element_num_cornersPK16t8_eclass_schemePK10t8_element
000000000005edb0 T _ZNK26t8_default_scheme_common_c22t8_element_num_cornersEPK10t8_element
00000000000671c0 T _ZNK27t8_default_scheme_pyramid_c22t8_element_num_cornersEPK10t8_element
```

With the fix in https://github.com/DLR-AMR/t8code/pull/379 I get:
```
nm libt8.so | grep t8_element_num_corners
0000000000033ea0 T t8_element_num_corners
000000000005edb0 T _ZNK26t8_default_scheme_common_c22t8_element_num_cornersEPK10t8_element
00000000000671c0 T _ZNK27t8_default_scheme_pyramid_c22t8_element_num_cornersEPK10t8_element
```

**Comment by jandrej** [comment] 2022-12-12 18:51
@holke @jmark I think the solution is to consistently define the const parameter and introduce this diff
```diff
diff --git a/src/t8_element_c_interface.h b/src/t8_element_c_interface.h
index 1d32f9d1..0d196e16 100644
--- a/src/t8_element_c_interface.h
+++ b/src/t8_element_c_interface.h
@@ -139,7 +139,7 @@ void                t8_element_sibling (t8_eclass_scheme_c *ts,
  * \param [in] elem   The element.
  * \return            The number of corners of \a element.
  */
-int                 t8_element_num_corners (t8_eclass_scheme_c *ts,
+int                 t8_element_num_corners (const t8_eclass_scheme_c *ts,
                                             const t8_element_t *elem);
 
 /** Compute the number of faces of an element.
 ```

**Closed** 2022-12-13 10:19 UTC
