### ISSUE TITLE
Failing program tests when building

### ISSUE THREAD

**Issue by alecontri** [DLR-AMR/t8code#1093] opened 2024-06-19 20:34 UTC
Hi,
 
I am trying to test your software on my laptop, but some test programs fail. The installation proceeds fine until the command `make check` or `make -j check`. I am building with the ‘quick release’ flags suggested 
`configure CFLAGS="-O3" CXXFLAGS="-O3" --enable-mpi CC=mpicc CXX=mpicxx`
These are the failing tests:
FAIL: test/t8_forest/t8_gtest_ghost_exchange
FAIL: test/t8_forest/t8_gtest_ghost_and_owner
FAIL: test/t8_forest/t8_gtest_forest_commit
 
Any suggestion on what could be the problem?
 
As a side note, a cascade of warnings from the system requesting permission to ‘accept incoming network connections’ is generated, I guess because of the way the parallel code is tested. Are you aware of a way to avoid this behaviour?

 
Some specs of my system are:
Apple M1 Pro – Ventura 13.5.1
Make 3.81
Automake 1.16.5

Thanks a lot for any help,
Alessandro

**Comment by Davknapp** [comment] 2024-06-20 07:26
Hey Alessandro,

thank you for publishing this Issue. It might be related to #1083 . 
During testing a log-file is produced for each test, can you add it to this issue? It will make it easier for us to solve it. 

Thank you!

**Comment by holke** [comment] 2024-06-20 08:48
Hi Alessandro,
thank you for posting this issue.
As David says, the log file would help a lot.
It is called `test-suite.log`

**Comment by holke** [comment] 2024-06-20 10:25
I could replicate the behaviour on my Macbook.


```bash
[libsc 0] Abort: Assertion 'forest->set_level <= forest->maxlevel'
[libsc 0] libsc 1] Abort: Assertion 'forest->set_level <= forest->maxlevel'
[libsc 1] Abort: ../../source/t8code/src/t8_forest/t8_forest.c:454
Abort: ../../source/t8code/src/t8_forest/t8_forest.c:454
```

```
[libsc 0] Abort: Assertion 'rc->refcount > 0'
[libsc 0] Abort: ../../../source/t8code/sc/src/sc_refcount.c:83
[libsc 0] Abort: Obtained 13 stack frames
[libsc 0] Stack 0: 0   libsc.2.dylib                       0x00000001031131f4 sc_abort_handler + 96
[libsc 0] Stack 1: 1   libsc.2.dylib                       0x00000001031132fc sc_abort + 20
[libsc 0] Stack 2: 2   libsc.2.dylib                       0x0000000103111d98 sc_malloc + 0
[libsc 0] Stack 3: 3   libsc.2.dylib                       0x00000001031271f0 sc_refcount_is_active + 0
[libsc 0] Stack 4: 4   libt8.2.dylib                       0x0000000103190f44 t8_cmesh_unref + 44
[libsc 0] Stack 5: 5   t8_gtest_iterate_replace            0x0000000102bea390 _ZN7testing8internal35HandleExceptionsInMethodIfSupportedINS_4TestEvEET0_PT_MS4_FS3_vEPKc + 92
[libsc 0] Stack 6: 6   t8_gtest_iterate_replace            0x0000000102beb718 _ZN7testing8TestInfo3RunEv + 512
[libsc 0] Stack 7: 7   t8_gtest_iterate_replace            0x0000000102bec204 _ZN7testing9TestSuite3RunEv + 388
[libsc 0] Stack 8: 8   t8_gtest_iterate_replace            0x0000000102bf9900 _ZN7testing8internal12UnitTestImpl11RunAllTestsEv + 1272
[libsc 0] Stack 9: 9   t8_gtest_iterate_replace            0x0000000102bf92e4 _ZN7testing8internal35HandleExceptionsInMethodIfSupportedINS0_12UnitTestImplEbEET0_PT_MS4_FS3_vEPKc + 92
[libsc 0] Stack 10: 10  t8_gtest_iterate_replace            0x0000000102bf9254 _ZN7testing8UnitTest3RunEv + 128
[libsc 0] Stack 11: 11  t8_gtest_iterate_replace            0x0000000102bc9338 main + 92
[libsc 0] Stack 12: 12  dyld                                0x00000001899fd0e0 start + 2360
Abort(1) on node 0 (rank 0 in comm 0): application called MPI_Abort(MPI_COMM_WORLD, 1) - process 0
FAIL test/t8_forest_incomplete/t8_gtest_iterate_replace (exit status: 1)

```
[test-suite.log](https://github.com/user-attachments/files/15912360/test-suite.log)

**Comment by alecontri** [comment] 2024-06-21 04:56
Hi,

sorry for the late reply. Here is the `test_suite.log` files in the build directory, folders /sc and /p4test. I may mention here that the `make -j check` command never terminated since the process was still going after 3 hours and I had to kill it. Do you have an estimate more or less on how long I have to let it run on a laptop to complete the tests?
[test-suite.log](https://github.com/user-attachments/files/15922895/test-suite.log)
[test-suite.log](https://github.com/user-attachments/files/15922898/test-suite.log)


Thanks you for the help,
Alessandro

**Comment by holke** [comment] 2024-06-21 07:58
Hi Alessandro, the full test-suite usually takes less than 10 minutes.
30 on slow machines.

So 3 hours is definitely too high.

Good news we identified the cause (or at least one) of the failing tests and are working on a solution.

It is only affecting 0 dimensional edge cases.
So you should be safe to use t8code nevertheless.

**Comment by Davknapp** [comment] 2024-06-24 07:47
One of our latests PR introduced new tests and increased the runtime by quite a lot. The current main branch include a PR that reduces the runtime of our testsuite to a manageable amount of time, if your problem persists, it might be a good idea to update to the current version of our main-branch.

**Comment by holke** [comment] 2024-06-25 08:35
Hi @alecontri 
we just merged a bugfix and the tests 

 test/t8_forest/t8_gtest_ghost_exchange
 test/t8_forest/t8_gtest_ghost_and_owner
 test/t8_forest/t8_gtest_forest_commit

should be passing now.

The test t8_forest_incomplete/t8_gtest_iterate_replace
is still failing on Mac (for you as well?) and we are investigating. See #1083

**Closed** 2024-06-25 08:35 UTC

**Comment by alecontri** [comment] 2024-07-06 18:12
I apologize for the late reply. I confirm that I had no issues after the fix, not even with the test t8_forest_incomplete/t8_gtest_iterate_replace test. Thanks a lot!
